{% set name = "pybaselines" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f61ca378459af3983d6ca5813610ca587ac33d5b89e3c03bfb5f692bde61526

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=64
  run:
    - numpy >=1.20
    - python >=3.8
    - scipy >=1.5
  run_constrained:
    - numba >=0.49
    - pentapy >=1.1

test:
  imports:
    - pybaselines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/derb12/pybaselines
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - LICENSES_bundled.txt
  doc_url: https://pybaselines.readthedocs.io
  dev_url: https://github.com/derb12/pybaselines
  summary: A library of algorithms for the baseline correction of experimental data.
  description: |
    pybaselines is a Python library that provides many different
    algorithms for performing baseline correction on data from
    experimental techniques such as Raman, FTIR, NMR, XRD, etc.

extra:
  recipe-maintainers:
    - derb12
