{% set name = "pybaselines" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86ba724c95bf13e6e20c0bb6caad0b7470db4d4d125392dfb0b0257e2c6f4c13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.14
    - python >=3.6
    - scipy >=1.0
  run_constrained:
    - numba >=0.45
    - pentapy >=1.0

test:
  imports:
    - pybaselines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/derb12/pybaselines
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - LICENSES_bundled.txt
  doc_url: https://pybaselines.readthedocs.io
  dev_url: https://github.com/derb12/pybaselines
  summary: A library of algorithms for the baseline correction of experimental data.
  description: |
    pybaselines is a Python library that provides many different
    algorithms for performing baseline correction on data from
    experimental techniques such as Raman, FTIR, NMR, XRD, etc.

extra:
  recipe-maintainers:
    - derb12
