{% set name = "pybaselines" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60b191fc3f9088ccd763b51cac16a990fa8198da7392c15d586453d40b837d8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.27
  run:
    - numpy >=1.20
    - python >={{ python_min }}
    - scipy >=1.6
  run_constrained:
    - numba >=0.53
    - pentapy >=1.1

test:
  imports:
    - pybaselines
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/derb12/pybaselines
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - LICENSES_bundled.txt
  doc_url: https://pybaselines.readthedocs.io
  dev_url: https://github.com/derb12/pybaselines
  summary: A library of algorithms for the baseline correction of experimental data.
  description: |
    pybaselines is a Python library that provides many different
    algorithms for performing baseline correction on data from
    experimental techniques such as Raman, FTIR, NMR, XRD, etc.

extra:
  recipe-maintainers:
    - derb12
